//......................................
// #CAUTION: Do not delete this file. //
//......................................
//Validator for Featured Events for Home Screen Data -Start -->>
var contains_data = false;
//-Ends here->>
